/* auto-generated by scripts/generate-avatar-manifest.mjs */
import type { AvatarManifest } from "./types";

const manifest: AvatarManifest = {
  "loops": {
    "idle_neutral": [
      {
        "id": "idle_neutral_0",
        "kind": "loop",
        "state": "idle_neutral",
        "src": "/avatar/loops/idle_neutral/idle_neutral_0.gif",
        "durationMs": 2292,
        "format": "gif"
      },
      {
        "id": "idle_neutral_1",
        "kind": "loop",
        "state": "idle_neutral",
        "src": "/avatar/loops/idle_neutral/idle_neutral_1.gif",
        "durationMs": 5042,
        "format": "gif"
      },
      {
        "id": "idle_neutral_2",
        "kind": "loop",
        "state": "idle_neutral",
        "src": "/avatar/loops/idle_neutral/idle_neutral_2.gif",
        "durationMs": 5042,
        "format": "gif"
      }
    ],
    "warm_friendly": [
      {
        "id": "warm_friendly_1",
        "kind": "loop",
        "state": "warm_friendly",
        "src": "/avatar/loops/warm_friendly/warm_friendly_1.gif",
        "durationMs": 5042,
        "format": "gif"
      },
      {
        "id": "warm_friendly_2",
        "kind": "loop",
        "state": "warm_friendly",
        "src": "/avatar/loops/warm_friendly/warm_friendly_2.gif",
        "durationMs": 5042,
        "format": "gif"
      },
      {
        "id": "warm_friendly_3",
        "kind": "loop",
        "state": "warm_friendly",
        "src": "/avatar/loops/warm_friendly/warm_friendly_3.gif",
        "durationMs": 5042,
        "format": "gif"
      }
    ],
    "listening_attentive": [
      {
        "id": "listening_attentive_1",
        "kind": "loop",
        "state": "listening_attentive",
        "src": "/avatar/loops/listening_attentive/listening_attentive_1.gif",
        "durationMs": 5042,
        "format": "gif"
      },
      {
        "id": "listening_attentive_2",
        "kind": "loop",
        "state": "listening_attentive",
        "src": "/avatar/loops/listening_attentive/listening_attentive_2.gif",
        "durationMs": 5042,
        "format": "gif"
      }
    ],
    "thinking_process": [
      {
        "id": "thinking_process_1",
        "kind": "loop",
        "state": "thinking_process",
        "src": "/avatar/loops/thinking_process/thinking_process_1.gif",
        "durationMs": 1792,
        "format": "gif"
      }
    ],
    "speaking_explain": [
      {
        "id": "speaking_explain_1",
        "kind": "loop",
        "state": "speaking_explain",
        "src": "/avatar/loops/speaking_explain/speaking_explain_1.gif",
        "durationMs": 5042,
        "format": "gif"
      },
      {
        "id": "speaking_explain_2",
        "kind": "loop",
        "state": "speaking_explain",
        "src": "/avatar/loops/speaking_explain/speaking_explain_2.gif",
        "durationMs": 5042,
        "format": "gif"
      }
    ],
    "positive_happy": [
      {
        "id": "positive_happy_1",
        "kind": "loop",
        "state": "positive_happy",
        "src": "/avatar/loops/positive_happy/positive_happy_1.gif",
        "durationMs": 5042,
        "format": "gif"
      },
      {
        "id": "positive_happy_2",
        "kind": "loop",
        "state": "positive_happy",
        "src": "/avatar/loops/positive_happy/positive_happy_2.gif",
        "durationMs": 5042,
        "format": "gif"
      }
    ]
  },
  "transitions": {
    "tr_idle_neutral_to_listening_attentive": {
      "id": "tr_idle_neutral_to_listening_attentive",
      "kind": "transition",
      "from": "idle_neutral",
      "to": "listening_attentive",
      "src": "/avatar/transitions/tr_idle_neutral_to_listening_attentive.gif",
      "reverseSrc": new URL("../../../generated/avatar/reverse/tr_idle_neutral_to_listening_attentive__rev.gif", import.meta.url).href,
      "durationMs": 5083,
      "format": "gif"
    },
    "tr_idle_neutral_to_speaking_explain": {
      "id": "tr_idle_neutral_to_speaking_explain",
      "kind": "transition",
      "from": "idle_neutral",
      "to": "speaking_explain",
      "src": "/avatar/transitions/tr_idle_neutral_to_speaking_explain.gif",
      "reverseSrc": new URL("../../../generated/avatar/reverse/tr_idle_neutral_to_speaking_explain__rev.gif", import.meta.url).href,
      "durationMs": 3083,
      "format": "gif"
    },
    "tr_idle_neutral_to_warm_friendly": {
      "id": "tr_idle_neutral_to_warm_friendly",
      "kind": "transition",
      "from": "idle_neutral",
      "to": "warm_friendly",
      "src": "/avatar/transitions/tr_idle_neutral_to_warm_friendly.gif",
      "reverseSrc": new URL("../../../generated/avatar/reverse/tr_idle_neutral_to_warm_friendly__rev.gif", import.meta.url).href,
      "durationMs": 2000,
      "format": "gif"
    },
    "tr_listening_attentive_to_thinking_process": {
      "id": "tr_listening_attentive_to_thinking_process",
      "kind": "transition",
      "from": "listening_attentive",
      "to": "thinking_process",
      "src": "/avatar/transitions/tr_listening_attentive_to_thinking_process.gif",
      "reverseSrc": new URL("../../../generated/avatar/reverse/tr_listening_attentive_to_thinking_process__rev.gif", import.meta.url).href,
      "durationMs": 5083,
      "format": "gif"
    },
    "tr_speaking_explain_to_positive_happy": {
      "id": "tr_speaking_explain_to_positive_happy",
      "kind": "transition",
      "from": "speaking_explain",
      "to": "positive_happy",
      "src": "/avatar/transitions/tr_speaking_explain_to_positive_happy.gif",
      "reverseSrc": new URL("../../../generated/avatar/reverse/tr_speaking_explain_to_positive_happy__rev.gif", import.meta.url).href,
      "durationMs": 2583,
      "format": "gif"
    },
    "tr_thinking_process_to_speaking_explain": {
      "id": "tr_thinking_process_to_speaking_explain",
      "kind": "transition",
      "from": "thinking_process",
      "to": "speaking_explain",
      "src": "/avatar/transitions/tr_thinking_process_to_speaking_explain.gif",
      "reverseSrc": new URL("../../../generated/avatar/reverse/tr_thinking_process_to_speaking_explain__rev.gif", import.meta.url).href,
      "durationMs": 2944,
      "format": "gif"
    },
    "tr_warm_friendly_to_listening_attentive": {
      "id": "tr_warm_friendly_to_listening_attentive",
      "kind": "transition",
      "from": "warm_friendly",
      "to": "listening_attentive",
      "src": "/avatar/transitions/tr_warm_friendly_to_listening_attentive.gif",
      "reverseSrc": new URL("../../../generated/avatar/reverse/tr_warm_friendly_to_listening_attentive__rev.gif", import.meta.url).href,
      "durationMs": 5083,
      "format": "gif"
    },
    "tr_warm_friendly_to_speaking_explain": {
      "id": "tr_warm_friendly_to_speaking_explain",
      "kind": "transition",
      "from": "warm_friendly",
      "to": "speaking_explain",
      "src": "/avatar/transitions/tr_warm_friendly_to_speaking_explain.gif",
      "reverseSrc": new URL("../../../generated/avatar/reverse/tr_warm_friendly_to_speaking_explain__rev.gif", import.meta.url).href,
      "durationMs": 5083,
      "format": "gif"
    }
  }
};

export default manifest;
